-- phpMyAdmin SQL Dump
-- Host: localhost
-- Database: db_masjid

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+07:00";

-- Tabel Users (Untuk Login Admin)
CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `username` varchar(50) NOT NULL,
  `email` varchar(100) NOT NULL,
  `password` varchar(255) NOT NULL,
  `image` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabel Profil Masjid
CREATE TABLE IF NOT EXISTS `profiles` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(150) NOT NULL DEFAULT 'Masjid Al-Ikhlas',
  `history` text NOT NULL,
  `vision` text NOT NULL,
  `mission` text NOT NULL,
  `logo` varchar(255) DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL,
  `hero_image` varchar(255) DEFAULT NULL,
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabel Manajemen Masjid (Program & Layanan)
CREATE TABLE IF NOT EXISTS `mosque_managements` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(150) NOT NULL,
  `description` text NOT NULL,
  `icon` varchar(50) NOT NULL, -- Contoh: 'fa-solid fa-book-quran'
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabel Artikel
CREATE TABLE IF NOT EXISTS `articles` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `content` text NOT NULL,
  `image` varchar(255) DEFAULT NULL,
  `category` varchar(100) NOT NULL,
  `user_id` int(11) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabel Organisasi (Pengurus)
CREATE TABLE IF NOT EXISTS `organizations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(150) NOT NULL,
  `position` varchar(100) NOT NULL,
  `image` varchar(255) DEFAULT NULL,
  `linkedin` varchar(255) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabel Kontak
CREATE TABLE IF NOT EXISTS `contacts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `address` text NOT NULL,
  `phone` varchar(50) NOT NULL,
  `whatsapp` varchar(50) NOT NULL,
  `email_1` varchar(100) NOT NULL,
  `email_2` varchar(100) DEFAULT NULL,
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Insert Default Admin Data (Password: admin123)
-- hash = $2y$10$xUelVnnMXgmL7D.lM3TYoud29kjSw.U1Jsw8ZR5k9BIFc3c5UGXZe (Generated by password_hash('admin123', PASSWORD_DEFAULT))
INSERT INTO `users` (`name`, `username`, `email`, `password`) VALUES
('Admin Utama', 'admin', 'admin@masjidalikhlas.org', '$2y$10$xUelVnnMXgmL7D.lM3TYoud29kjSw.U1Jsw8ZR5k9BIFc3c5UGXZe')
ON DUPLICATE KEY UPDATE `password` = VALUES(`password`);

-- Insert Default Profil Data
INSERT INTO `profiles` (`name`, `history`, `vision`, `mission`) VALUES
('Masjid Al-Ikhlas', 'Masjid Al-Ikhlas didirikan pada tahun 1998 atas inisiatif warga sekitar yang menginginkan pusat ibadah yang dekat dan nyaman. Dibangun di atas tanah wakaf seluas 2000 meter persegi, masjid ini telah mengalami beberapa kali renovasi untuk mengakomodasi jumlah jamaah yang terus bertambah dan memperluas fungsi masjid sebagai pusat pendidikan dan sosial.', 'Menjadi masjid paripurna sebagai pusat pembinaan umat yang bertaqwa, cerdas, dan mandiri berlandaskan Al-Qur\'an dan As-Sunnah.', '<li>Menyelenggarakan peribadatan yang sesuai dengan tuntunan syariat.</li><li>Meningkatkan kualitas pendidikan Islam bagi anak-anak dan dewasa.</li><li>Memberdayakan ekonomi umat melalui ZISWAF.</li>')
ON DUPLICATE KEY UPDATE `history` = VALUES(`history`);

-- Insert Default Management Data
INSERT INTO `mosque_managements` (`title`, `description`, `icon`) VALUES
('Pendidikan & Dakwah', 'Penyelenggaraan Taman Pendidikan Al-Qur\'an (TPQ), kajian rutin harian, tahsin untuk dewasa, dan majelis taklim pekanan.', 'fa-book-quran'),
('Baitul Mal (ZISWAF)', 'Pengelolaan Zakat, Infaq, Shadaqah, dan Wakaf secara profesional dan transparan untuk disalurkan kepada yang berhak menerima.', 'fa-hand-holding-dollar'),
('Sosial & Kesehatan', 'Layanan ambulan gratis, klinik kesehatan masjid, santunan anak yatim dan dhuafa, serta tanggap bencana alam.', 'fa-kit-medical');

-- Insert Default Contacts Data
INSERT INTO `contacts` (`address`, `phone`, `whatsapp`, `email_1`, `email_2`) VALUES
('Jl. Pangeran Diponegoro No. 123, Kelurahan Suka Maju, Kecamatan Damai, Kota Sejahtera, 12345', '(021) 1234-5678', '+62 812-3456-7890', 'info@masjidalikhlas.org', 'takmir@masjidalikhlas.org')
ON DUPLICATE KEY UPDATE `address` = VALUES(`address`);

COMMIT;
